"""initial migration

Revision ID: 071a5c2f42ae
Revises: 
Create Date: 2021-04-29 11:14:42.445945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071a5c2f42ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='upload_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'upload_info', ['name'], unique=True)
    # ### end Alembic commands ###
