"""primary version of db

Revision ID: 8daa736c7a78
Revises: 
Create Date: 2021-04-30 13:49:12.946592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8daa736c7a78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_info',
    sa.Column('User_Account_ID', sa.Integer(), nullable=False),
    sa.Column('Invoice_Number', sa.String(length=10), nullable=True),
    sa.Column('Amount', sa.Integer(), nullable=True),
    sa.Column('Fees', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('User_Account_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_info')
    # ### end Alembic commands ###
